apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-one
  template:
    metadata:
      labels:
        app: svc-one
    spec:
      containers:
      - name: svc-one
        image: svc-one:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always

