apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-two
  template:
    metadata:
      labels:
        app: svc-two
    spec:
      containers:
      - name: svc-two
        image: svc-two:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
      restartPolicy: Always
